services:
  # Laravel API
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: e-commerce-api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./api:/var/www
      - ./api/docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - e-commerce-network
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: e-commerce-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_USER: ${DB_USERNAME:-laravel}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - e-commerce-network

networks:
  e-commerce-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
