services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000

  nuxt:
    build:
      context: ../app
      dockerfile: Dockerfile
    container_name: nuxt-app
    restart: unless-stopped
    working_dir: /app
    environment:
      - NUXT_SANCTUM_BASE_URL=http://app:8000
      - NUXT_SANCTUM_ORIGIN=http://localhost:3000
    volumes:
      - ../app:/app
      - /app/node_modules
      - /app/.nuxt
      - /app/.output
    networks:
      - laravel
    depends_on:
      - app
    ports:
      - "3000:3000"
    command: npm run dev

  db:
    image: mysql:8.0
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_USER: ${DB_USERNAME:-laravel}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
    ports:
      - "8080:80"
    networks:
      - laravel
    depends_on:
      - db

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
    driver: local
